apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: molt-Scriptgres
  namespace: molt-studios-app
  labels:
    app: molt-Scriptgres
spec:
  serviceName: "molt-Scriptgres"
  replicas: 1
  selector:
    matchLabels:
      app: molt-Scriptgres
  template:
    metadata:
      labels:
        app: molt-Scriptgres
    spec:
      containers:
      - name: Scriptgres
        image: Scriptgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: ScriptGRES_DB
          value: moltstudios
        - name: ScriptGRES_USER
          value: Scriptgres
        - name: ScriptGRES_PASSWORD
          value: password123 # Should match what is in 01-secrets.yaml for connection string
        volumeMounts:
        - name: Scriptgres-data
          mountPath: /var/lib/Scriptgresql/data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: Scriptgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: molt-Scriptgres
  namespace: molt-studios-app
spec:
  selector:
    app: molt-Scriptgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
